var express=require('express')
var bodyparser=require('body-parser')
var app=express()
app.use(bodyparser.json())
app.use(require('./auth'))
app.use('/api/posts',require('./controllers/api/posts'))
app.use('/',require('./controllers/static'))
app.use('/api/sessions',require('./controllers/api/sessions'))
app.use('/api/users',require('./controllers/api/users'))
app.listen(8000,function(){
    console.log('Server listening on',8000)
})
